### PR TITLE
[Viame] Merge in v0.10.0

### PR DESCRIPTION
**Pull request by neal-siekierski**
This PR merges in the `v0.10.0` tag. The most relevant part of v0.10.0 for me is that the Faiss wrapper works.

The merge was mostly clean, with conflicts limited to:
- `python/smqtk/algorithms/relevancy_index/libsvm_hik.py`
- `python/smqtk/iqr/iqr_session.py`
- `python/smqtk/representation/descriptor_index/postgres.py`
- `python/smqtk/tests/algorithms/relevancy_index/test_svm_hik.py`

Most of these seemed straightforward to resolve.

The current validation status is "works for me" &ndash; with Viame built against an SMQTK with these changes I remain able to do a video ingest, create a ball-tree index, and use the ingested video and index to perform IQR in the GUI. Faiss can also be made to work.

### CODE REVIEW

**Comment by neal-siekierski** [comment]
The earlier merge-in of v0.9.0 appears to have messed up `test_svm_hik.py`, plus I didn't need make some needed changes. Re-pushing.

**Comment by neal-siekierski** [comment]
Ah, I see where the remaining test failure is coming from. Commit ca394455b3d86e138bcbd4ada2cd7024c146b935 (on `viame/master`) and commits 93ad0e4847658e947d7530ea9bed6ab3e7408256^..fdc5aba173e1d9ab75fd42de05769b6492f6f3f7 (part of #339, in `master`) both try to solve an issue with `libsvm.svm_save_model` in `libsvm`'s Python wrapping having trouble accepting Python 3's strings, but the result is that they try to encode a string twice, which you can't do.

I see three options here:
- Revert commits 93ad0e4847658e947d7530ea9bed6ab3e7408256^..fdc5aba173e1d9ab75fd42de05769b6492f6f3f7 and also expand on commit ca394455b3d86e138bcbd4ada2cd7024c146b935 to cover all the other functions in `svmutil.py` that take file names. Document that they always take string paths.
- Revert commit ca394455b3d86e138bcbd4ada2cd7024c146b935 and ensure that `viame/master` didn't introduce any other problematic uses of the `svmutil` functions. Document that they always take byte paths.
- Expand on commit ca394455b3d86e138bcbd4ada2cd7024c146b935 to let all functions in `smvutil.py` take `str`- or `bytes`-typed paths.

My preference is for the first option. The relevant changes would then ideally be merged into `master`. 

@Purg @mattdawkins: Thoughts?

**Comment by Purg** [comment]
I am more on the side of option 2 due to how I think libsvm should be treated as an external dependency (we should be moving towards removing libsvm/flann from the smqtk repository).  Given however that the viame/master branch has moved to make other modifications to the included libsvm fork that lock SMQTK to using it, either is option is probably fine

**Comment by neal-siekierski** [comment]
@Purg, that's a fair point, not to mention that taking the first option would increase the divergence from upstream. I've opted for the second option.

@mattdawkins, I expect this resolution to cause minor breakage in VIAME, but something like https://github.com/Kitware/VIAME/compare/dev/update_smqtk_to_v0.10.0?expand=1 should fix it.

**Pull request merged**
