### PR TITLE
Only use magic if the input filepath actually points to a real file

### PR DESCRIPTION
**Pull request by Purg**
``file-magic`` obviously fails if there are no bytes to introspect for a
file type. Fixed tests to pass when file-magic is installed.

### CODE REVIEW

**Comment by Purg** [comment]
@danlamanna @fishcorn PTAL

**Comment by danlamanna** [comment]
This LGTM.

Tangentially related, why isn't this block of logic in the `content_type` method?

**Comment by Purg** [comment]
On line 66? The python mimetypes module literally only uses the filepath string extension to guess, so the file doesn't actually need to exist on disk.

**Comment by fishcorn** [comment]
LGTM

Incidentally, this should solve my latest problem. I was having a path issue in my image list file, which triggered that python 2.7 bug in file-magic I talked to @Purg about.

**Pull request merged**
