### PR TITLE
Add setup.py installation support

### PR DESCRIPTION
**Pull request by Purg**
Cleaning up requirements, adding setup.py installation support and reorganizing files/CMake as necessary. For example, removing CPack stuff at the end of top-level CMake lists as ``setup.py`` and pip is our packaging.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
I was able to pip install smqtk on my Mac. I was surprised however that there is nothing imported by default:

```
>>> import smqtk
>>> dir(smqtk)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
```

Seems that `python/smqtk/__init__.py` should import some things (everything?) by default instead of being empty.

**Comment by Purg** [comment]
I suppose nothing is imported because I don't know exactly what to import. Should probably address that on a different branch, though. Could ``import *`` from the ``algorithm`` and ``representation`` sub-modules, I guess.

**Comment by jeffbaumes** [comment]
Yeah another branch would be fine. Awesome that pip install works and also doesn't take super long (maybe 30 seconds on mac).

**Comment by Purg** [comment]
Only ~1.4MB. It helps when you don't have to pull down ghost code archives in the git object history.

**Comment by jeffbaumes** [comment]
Knowing SMQTK's storied past, 👍  to avoid those historical Git objects

**Pull request merged**
