### PR TITLE
Create initial github actions workflow for CI

### PR DESCRIPTION
**Pull request by Purg**
Attempt running unit tests via github actions as a new CI running platform.

Resources referenced:
* https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
* https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
* https://github.com/numpy/numpy/blob/master/.github/workflows/build_test.yml
* https://github.com/numpy/numpy/blob/master/.github/actions/action.yml

### CODE REVIEW

**Comment by Purg** [comment]
@waxlamp the draft experiment to use github actions for CI.

**Comment by waxlamp** [comment]
> @waxlamp the draft experiment to use github actions for CI.

This all looks great. I would remove most or all of the tutorial-style comments but other than that, not bad at all.

When this is marked as non-draft, I can provide a formal review if you want (just use the "request review" thing).

**Comment by Purg** [comment]
I'll remove some of the more egregious "tutorial" comments. I want to keep a bunch in there that's informational when inevitably someone wants/needs to look at this and doesn't already have a context as to what's happening.

**Comment by Purg** [comment]
Since this is subsuming the Travis-CI based things, I'll want to remove that config here as well as from SMQTK repository settings.

**Comment by Purg** [comment]
Changed check requirements settings on SMQTK to match new setup.

**Review by waxlamp — APPROVED** [review]

**Pull request merged**
