### PR TITLE
Switch lib to dll for windows libsvm

### PR DESCRIPTION
**Pull request by hughed2**

### CODE REVIEW

**Comment by hughed2** [comment]
Switching to dev/begin-windows-support so Dawkins can do what he needs to.

**Comment by Purg** [comment]
@mattdawkins ?

**Comment by mattdawkins** [comment]
I don't believe this is the only problem, I think the dll is being installed to the wrong location but I'll merge this into the windows branch

**Comment by Purg** [comment]
We can have multiple branches to fix multiple problems. :)

**Comment by hughed2** [comment]
@mattdawkins I'll take another look, but I'm pretty sure correcting the typo should fix it. We move a bunch of files, including ${LIBSVM_NAME} from the source directory to ${TPL_LOCAL_INSTALL}. Since ${LIBSVM_NAME} wasn't set correctly on windows, our dll was never getting moved.

**Pull request merged**
