### PR TITLE
Patch/fix iqr playground docker

### PR DESCRIPTION
**Pull request by Purg**
Patch update to SMQTK to fix IQR docker image functionality for toolkit updates since last revision.  This mainly fixes/updates:

- docker image OS version to Xenial (and nvidia/cuda image from 8.0 to 8.0-cudnn7-devel)
- caffe 1 version (and its dependencies) to 1.0.
- fix (by updating) mongo installation
- configuration file updates for updated APIs

### CODE REVIEW

**Comment by Purg** [comment]
PTAL @wphicks @danlamanna 

Link anyone else who you think might be more appropriate.

**Comment by wphicks** [comment]
The IQR Playground docker image is failing to build for me with the following error:
```
E: The method driver /usr/lib/apt/methods/https could not be found.
E: Failed to fetch https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/InRelease 
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5  && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse"     | tee /etc/apt/sources.list.d/mongodb-org-3.6.list  && apt-get -y update  && apt-get -y install mongodb-org=3.6.5' returned a non-zero code: 100
```

**Comment by chrismattmann** [comment]
@Purg does this work with CPU too?

**Comment by Purg** [comment]
@chrismattmann I believe that I equivalently fixed CPU and GPU dockerfiles.

**Comment by Purg** [comment]
Sorry for this stuff not moving very quick, I've been pretty loaded up for the past few weeks.  The `devops/docker/smqtk_iqr_playground/README.md` file (co-located with the associated Docker image context) should detail how to use the result Docker image.

**Comment by Purg** [comment]
@wphicks Either there was an apt repo hickup or I'm missing an install of a https apt driver package (I remember this being an issue in other images I've created dockerfiles for).  I'll check on this when I have a free moment.

**Comment by Purg** [comment]
Closing this PR because it is superseded by changes to master with release 0.10.0.

**Pull request closed without merging**
