### PR TITLE
Updated IQR docker image README for better clarity of instruction

### PR DESCRIPTION
**Pull request by Purg**
Amended IQR docker image README.md file to provide more clarity in building and running the docker images.

### CODE REVIEW

**Comment by Purg** [comment]
PTAL @chrismattmann and @bhshah

**Comment by Purg** [comment]
Rebased on current master.

**Comment by Purg** [comment]
Also PTAL @wphicks in case you see anything obvious.

**Comment by chrismattmann** [comment]
doco updates look +1 to me. I have a PR coming to fix the Caffe SMQTK docker build, coming separately :) +1 from me @Purg

**Pull request merged**
