### PR TITLE
Prune archive code

### PR DESCRIPTION
**Pull request by Purg**
Remove old GENIE/MASIR code that held no active purpose. Tag `before-genie-masir-prune` created to mark hash before these files were removed.

### CODE REVIEW

**Comment by Purg** [comment]
This isn't triggering CI correctly?

**Comment by Purg** [comment]
weird...

**Comment by jeffbaumes** [comment]
+1 :scissors: Is this why your username is @Purg (e) ?

**Comment by Purg** [comment]
Haha, longer story, but no. :)

**Pull request merged**
