### PR TITLE
script to cluster via MiniBatchKMeans (scikit-learn)

### PR DESCRIPTION
**Pull request by Purg**

### CODE REVIEW

**Comment by jeffbaumes** [comment]
May be good to have some docs/tests on this, but yay for scalable clustering!

**Comment by Purg** [comment]
Ok, I'll work on docs/testing today/evening.

**Comment by Purg** [comment]
Any other comments @jeffbaumes ?

**Comment by jeffbaumes** [comment]
Can't speak technically, but the test and method description LGTM, thanks.

**Comment by Purg** [comment]
Going to merge now then, and add more tests if/when bugs/errors appear.

**Pull request merged**
