### PR TITLE
implement ITQ in python

### PR DESCRIPTION
**Pull request by z-harry-sun**

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Yay ITQ! :tada: So will this take a large dataset and find the best way to compress the features? Or compress features given a mapping? Or efficiently query a collection of compressed features? Or all of the above?

**Comment by Purg** [comment]
Well, this is the first step in those directions...

From what Harry has explained to me so far (I haven't been able to dive into this yet) is that this is the code that we train and would produce the small-codes (the hash codes) for a given data-item/descriptor. A subclass to the SimilarityIndex interface still needs to be made, which will use this when building an index and performing the nearest-neightbor operation over that index. I will also need to probably abstract out how LSH/ITQ indices store their data (local vs. remote), since large scale LSH/ITQ indices will probably not fit well in RAM.

**Comment by jeffbaumes** [comment]
Yes, figured it would not be fully integrated at this point. Baby steps :footprints:

**Comment by aashish24** [comment]
What does ITQ  stands for?

**Comment by Purg** [comment]
Iterative Quantization
http://www.cs.unc.edu/~lazebnik/publications/cvpr11_small_code.pdf

On Mon, Jun 22, 2015 at 9:49 AM, Aashish Chaudhary <notifications@github.com
> wrote:

> What does ITQ stands for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/SMQTK/pull/85#issuecomment-114110438>.
>



-- 
Paul Tunison
R&D Engineer
Kitware, Inc.
28 Corporate Drive
Clifton Park, NY 12065 USA

Phone: (518) 371-3971 Ext.164

**Pull request merged**
