### PR TITLE
Dev/sphinx documentation

### PR DESCRIPTION
**Pull request by kfieldho**
This is an initial draft of Sphinx based documentation.  Soliciting feedback.  Ideally it would get merged fairly soon so that future development work get documented in this form.

One note: this branch also converts most of the utility scripts to use Python's argparse rather than optparse.  This is because there's a very useful extension to Sphinx that allows it to autodoc argparse objects.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Are you planning to host with readthedocs? I highly recommend it.

**Comment by kfieldho** [comment]
Yes, once this request is merged, arranging for updates on readthedocs is the next step.

**Comment by Purg** [comment]
Will hopefully get to this on my way back from DC or if I get ambitious this evening in the hotel.
This branch also needs a rebase. Github is telling me it's out-of-date.

**Comment by kfieldho** [comment]
I've rebased the branch.

**Comment by Purg** [comment]
This should probably also update the top-level README.md, either making that an RST version or removing the broken links there-in.

**Comment by Purg** [comment]
Awesome. Now a rebase I guess because Travis-CI is not cycling?

**Pull request merged**
